Add setitimer configuration option

diff --git a/debian/patches/06_551238_SMJS-FTBFS.diff b/debian/patches/06_551238_SMJS-FTBFS.diff
--- a/debian/patches/06_551238_SMJS-FTBFS.diff
+++ b/debian/patches/06_551238_SMJS-FTBFS.diff
@@ -16,7 +16,7 @@ index c463868..bcbebc0 100644
  CONFIG_FASTMEM = @CONFIG_FASTMEM@
  CONFIG_FINGER = @CONFIG_FINGER@
 diff --git a/configure b/configure
-index b8e22ce..36d7936 100755
+index b8e22ce..9df2deb 100755
 --- a/configure
 +++ b/configure
 @@ -709,6 +709,7 @@ SEE_CFLAGS
@@ -27,7 +27,106 @@ index b8e22ce..36d7936 100755
  SPIDERMONKEY_LIBS
  SPIDERMONKEY_CFLAGS
  CONFIG_SPIDERMONKEY
-@@ -18397,6 +18398,192 @@ _ACEOF
+@@ -13394,6 +13395,98 @@ _ACEOF
+ fi
+ done
+ 
++for ac_func in setitimer
++do
++as_ac_var=`echo "ac_cv_func_$ac_func" | $as_tr_sh`
++{ echo "$as_me:$LINENO: checking for $ac_func" >&5
++echo $ECHO_N "checking for $ac_func... $ECHO_C" >&6; }
++if { as_var=$as_ac_var; eval "test \"\${$as_var+set}\" = set"; }; then
++  echo $ECHO_N "(cached) $ECHO_C" >&6
++else
++  cat >conftest.$ac_ext <<_ACEOF
++/* confdefs.h.  */
++_ACEOF
++cat confdefs.h >>conftest.$ac_ext
++cat >>conftest.$ac_ext <<_ACEOF
++/* end confdefs.h.  */
++/* Define $ac_func to an innocuous variant, in case <limits.h> declares $ac_func.
++   For example, HP-UX 11i <limits.h> declares gettimeofday.  */
++#define $ac_func innocuous_$ac_func
++
++/* System header to define __stub macros and hopefully few prototypes,
++    which can conflict with char $ac_func (); below.
++    Prefer <limits.h> to <assert.h> if __STDC__ is defined, since
++    <limits.h> exists even on freestanding compilers.  */
++
++#ifdef __STDC__
++# include <limits.h>
++#else
++# include <assert.h>
++#endif
++
++#undef $ac_func
++
++/* Override any GCC internal prototype to avoid an error.
++   Use char because int might match the return type of a GCC
++   builtin and then its argument prototype would still apply.  */
++#ifdef __cplusplus
++extern "C"
++#endif
++char $ac_func ();
++/* The GNU C library defines this for functions which it implements
++    to always fail with ENOSYS.  Some functions are actually named
++    something starting with __ and the normal name is an alias.  */
++#if defined __stub_$ac_func || defined __stub___$ac_func
++choke me
++#endif
++
++int
++main ()
++{
++return $ac_func ();
++  ;
++  return 0;
++}
++_ACEOF
++rm -f conftest.$ac_objext conftest$ac_exeext
++if { (ac_try="$ac_link"
++case "(($ac_try" in
++  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
++  *) ac_try_echo=$ac_try;;
++esac
++eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
++  (eval "$ac_link") 2>conftest.er1
++  ac_status=$?
++  grep -v '^ *+' conftest.er1 >conftest.err
++  rm -f conftest.er1
++  cat conftest.err >&5
++  echo "$as_me:$LINENO: \$? = $ac_status" >&5
++  (exit $ac_status); } && {
++	 test -z "$ac_c_werror_flag" ||
++	 test ! -s conftest.err
++       } && test -s conftest$ac_exeext &&
++       $as_test_x conftest$ac_exeext; then
++  eval "$as_ac_var=yes"
++else
++  echo "$as_me: failed program was:" >&5
++sed 's/^/| /' conftest.$ac_ext >&5
++
++	eval "$as_ac_var=no"
++fi
++
++rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
++      conftest$ac_exeext conftest.$ac_ext
++fi
++ac_res=`eval echo '${'$as_ac_var'}'`
++	       { echo "$as_me:$LINENO: result: $ac_res" >&5
++echo "${ECHO_T}$ac_res" >&6; }
++if test `eval echo '${'$as_ac_var'}'` = yes; then
++  cat >>confdefs.h <<_ACEOF
++#define `echo "HAVE_$ac_func" | $as_tr_cpp` 1
++_ACEOF
++ HAVE_SETITIMER=yes
++fi
++done
+ 
+ 
+ for ac_func in cygwin_conv_to_full_win32_path
+@@ -18397,6 +18490,192 @@ _ACEOF
  fi
  done
  
@@ -220,6 +319,28 @@ index b8e22ce..36d7936 100755
  fi
  
  	CFLAGS="$CFLAGS_X";
+@@ -18476,6 +18755,21 @@ _ACEOF
+ 
+ 
+ 
++if test "x$CONFIG_ECMASCRIPT_SMJS" = xyes &&
++   test "x$HAVE_JS_TRIGGEROPERATIONCALLBACK" = xyes &&
++   test "x$HAVE_SETITIMER" = xyes; then
++
++	  CONFIG_ECMASCRIPT_SMJS_HEARTBEAT=yes
++	  ABOUT_CONFIG_ECMASCRIPT_SMJS_HEARTBEAT="ECMAScript heartbeat
++support"
++
++$as_echo "#define CONFIG_ECMASCRIPT_SMJS_HEARTBEAT 1" >>confdefs.h
++
++else
++	CONFIG_ECMASCRIPT_SMJS_HEARTBEAT=no
++fi
++
++
+ 
+ # ===================================================================
+ # Optional Spidermonkey-based ECMAScript browser scripting
 diff --git a/configure.in b/configure.in
 index 4a7143d..08c4bbc 100644
 --- a/configure.in
